http://localhost:3000
###
POST http://localhost:3000
###
POST http://localhost:3000/getpost
###
http://localhost:3000/getpost

### - Paramater in url
http://localhost:3000/hello/praveen

### - getdate from plugin

http://localhost:3000/getdate

### - Saving the user

POST http://localhost:3000/user
Content-Type: application/json

{
  "user": {
    "name": "Praveen",
    "lastname": "Sharma"
  }
}

### - Validation 3 to 10 chars should fail with 400
http://localhost:3000/hello/ab